### ISSUE TITLE
OSX 10.14.6, UE 4.26  - Failed to build RiderLink Plugin (ExitCode=6)  

### ISSUE THREAD

**Issue by Lykdraft** [JetBrains/UnrealLink#116]
Fails all the time, no dice...

Log:
[Log.txt](https://github.com/JetBrains/UnrealLink/files/6709983/Log.txt)

Log2:
[UBT-UE4Editor-Mac-Development.txt](https://github.com/JetBrains/UnrealLink/files/6709986/UBT-UE4Editor-Mac-Development.txt)

I've looked through those, I can't spot anything though...
Any ideas?

**Comment by ArtemiyAAA** [comment]
Hello, @Lykdraft 
Thank you for feedback.
This issue will be fixed in the next version.
Now you can install previous version:
- Load UnrealLink.zip here https://github.com/JetBrains/UnrealLink/releases/tag/v2021.1.10
- Use https://www.jetbrains.com/help/idea/managing-plugins.html#install_plugin_from_disk to install plugin from zip

**Comment by Lykdraft** [comment]
Yes, it is fixed in the latest version that dropped today.

Thanks a lot!
